/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetrePrincipale;

import java.awt.*;
import java.util.*;
import mesClasses.*;

/**
 *
 * @author guigui
 */
public class Bureau extends javax.swing.JFrame {
    private static Societe so;
    private static MySql bdd;
    
    /**
     * Creates new form Bureau
     */
    public Bureau() {
        bdd=new MySql();
        bdd.Connexion();
        so=new Societe("Stri", "Toulouse");
        so.ajouterLocal("local1", "bordeaux");
        so.ajouterLocal("local2", "bordeaux");
        so.ajouterSalle("local1", 0, 1, 15);
        so.ajouterSalle("local1", 0, 2, 20);
        initComponents();
        initialiseInterface();
    }

    public void initialiseInterface(){        
        ArrayList<Local> locaux=so.getLocaux();
        setLayout(new GridLayout(locaux.size(),1));
        for(Local loc:locaux){
            System.out.println(loc);
            add(new Button(loc.getNom()));
        }      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        AfficheLocaux = new javax.swing.JPanel();
        BarreMenu = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuQuitter = new javax.swing.JMenuItem();
        MenuAjouter = new javax.swing.JMenu();
        AjouterLocal = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout AfficheLocauxLayout = new javax.swing.GroupLayout(AfficheLocaux);
        AfficheLocaux.setLayout(AfficheLocauxLayout);
        AfficheLocauxLayout.setHorizontalGroup(
            AfficheLocauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        AfficheLocauxLayout.setVerticalGroup(
            AfficheLocauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        MenuFile.setText("Menu");

        MenuQuitter.setText("Exit");
        MenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQuitterActionPerformed(evt);
            }
        });
        MenuFile.add(MenuQuitter);

        BarreMenu.add(MenuFile);

        MenuAjouter.setText("Ajouter");

        AjouterLocal.setText("Ajouter Local");
        AjouterLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterLocalActionPerformed(evt);
            }
        });
        MenuAjouter.add(AjouterLocal);

        BarreMenu.add(MenuAjouter);

        setJMenuBar(BarreMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AfficheLocaux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AfficheLocaux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuQuitterActionPerformed
    
   
    
    private void AjouterLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjouterLocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bureau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bureau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AfficheLocaux;
    private javax.swing.JMenuItem AjouterLocal;
    private javax.swing.JMenuBar BarreMenu;
    private javax.swing.JMenu MenuAjouter;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuQuitter;
    private javax.swing.JDialog jDialog1;
    // End of variables declaration//GEN-END:variables
}
