/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetreLocal;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import mesClasses.*;

/**
 *
 * @author guigui
 */
public class FenetreSalle extends javax.swing.JPanel {
    private  ArrayList<Routeur> routeurs;
    private ArrayList<BorneSansFil> bornes;
    private MySql bdd;
    
    GridBagConstraints gbc=new GridBagConstraints();
    int positionX=0;
    int positionY=0;
        
    /**
     * Creates new form FenetreSalle
     * @param rout
     * @param bo
     */
    public FenetreSalle(ArrayList<Routeur> rout,ArrayList<BorneSansFil> bo) {
        
        
        /* bdd=new MySql();
        bdd.Connexion();*/
        initComponents();
        setLayout(new GridBagLayout());
        gbc.insets=new Insets(5, 5, 5, 5);
        gbc.gridx=10;
        gbc.gridy=10;    
        
        routeurs=rout;
        bornes=bo;
        setBackground(Color.WHITE);
        initialisationFenetre();
    }

    public void initialisationFenetre(){
        for(final Routeur rout:routeurs){
            final JButton bouton=new JButton("Mac: "+rout.getMac()+"/nom: "+rout.getNom());
            System.out.println(rout.toString());
            bouton.setName(rout.getMac());
            gbc.gridy=positionY;
            add(bouton,gbc);
            positionY++;
            bouton.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent arg0) {
                        setVisible(false);
                        FenetreOrdinateur f=new FenetreOrdinateur(rout);
                        add(f);
                        setVisible(false);
                        setVisible(true);
                }//fin actionPerf
                });       
        }
       for(BorneSansFil bo:bornes){
            final JButton localButton2=new JButton("Mac: "+bo.getMac()+"/nom: "+bo.getNom());
            localButton2.setName(bo.getMac());
            gbc.gridy=positionY;
            add(localButton2,gbc);
            positionY++;
           localButton2.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    /*routeurs=sa.getRouteurs();
                    bornes=sa.getBornes();
                    fenetreSalle=new FenetreSalle(routeurs,bornes);
                    add(fenetreSalle,BorderLayout.CENTER);
                    setVisible(false);
                    setVisible(true);*/
                }//fin actionPerf
                });          
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
