/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetreLocal;

/**
 *
 * @author guigui
 */
public class frame1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    public void initialisationMenuSalle(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSalle = new javax.swing.JPanel();

        setClosable(true);

        MenuSalle.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout MenuSalleLayout = new javax.swing.GroupLayout(MenuSalle);
        MenuSalle.setLayout(MenuSalleLayout);
        MenuSalleLayout.setHorizontalGroup(
            MenuSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        MenuSalleLayout.setVerticalGroup(
            MenuSalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(MenuSalle, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuSalle;
    // End of variables declaration//GEN-END:variables
}
