/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetreLocal;

import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import mesClasses.BorneSansFil;
import mesClasses.Equipement;
import mesClasses.MySql;
import mesClasses.Routeur;

/**
 *
 * @author guigui
 */
public class TableauEquipement extends javax.swing.JPanel {
    JTable tableau;
    private Equipement equipement;
    private String[] columns;
    private String[][] data;
    private MySql bdd;
    /**
     * Creates new form TableauEquipement
     */
    public TableauEquipement(Equipement equi) {
        equipement = equi;
        //initComponents();
        if (equipement instanceof BorneSansFil) {
            columns = new String[]{"Nom", "Mac", "Marque", "Power", "NomOS", "Version"};
        } else if (equipement instanceof Routeur) {
            columns = new String[]{"Nom", "Mac", "Marque", "Power", "Nombre de Port", "NomOS", "Version"};
        }
        data = new String[1][columns.length];
        initialiseTableau();
        tableau = new JTable(data, columns) {
            public boolean isCellEditable(int date, int colums) {
                System.out.println("date: " + date + " colums: " + colums);
                if (colums == 1 || colums == 2 || colums == 5 || colums == 4) {
                    return false;//si mac on peut la changer, marque, os
                }
                return true;
            }

            public Object getValueAt(int row, int col) {
                return data[row][col];
            }

            public void setValueAt(Object value, int row, int col) {
                bdd.Connexion();
                if (col != 1) {
                    data[row][col] = (String) value;
                    switch (col) {
                        case 0:
                            equipement.setNom((String) value);
                            bdd.ModifierNom(equipement.getNom(),equipement.getMac());
                            break;
                        case 3:
                            equipement.setPower(((String) value).equals("on"));
                            if (equipement instanceof Routeur) {
                                ((Routeur) equipement).activerDesactiverOrdinateur(((String) value).equals("on"));
                            } else if (equipement instanceof BorneSansFil) {
                                ((BorneSansFil) equipement).activerDesactiverTablette(((String) value).equals("on"));
                            }
                            bdd.ModifierEtat(equipement.isPower(),equipement.getMac());
                            break;
                    }
                }
            }

            public void addTableModelListener(TableModelListener l) {

            }
        };
        tableau.getTableHeader().setReorderingAllowed(false);
        tableau.setPreferredScrollableViewportSize(new Dimension(300, 600));
        tableau.setFillsViewportHeight(true);
        add(tableau);
        JScrollPane jps = new JScrollPane(tableau);
        add(jps);
    }

    public void initialiseTableau() {
        int i = 0;
        int j = 0;
        data[i][j] = equipement.getNom();
        j++;
        data[i][j] = equipement.getMac();
        j++;
        data[i][j] = equipement.getMarque();
        j++;
        data[i][j] = (equipement.isPower() ? "on" : "off");
        j++;
        if (equipement instanceof Routeur) {
            data[i][j] = ((Routeur) equipement).getNombrePorts().toString();
            j++;
        }
        data[i][j] = (equipement.getOs().getNomOs());
        j++;
        data[i][j] = (equipement.getOs().getVersion());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
