/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetreLocal;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import mesClasses.*;
import java.lang.*;
/**
 *
 * @author guigui
 */
public class Tableau extends javax.swing.JPanel {
    JTable tableau;
    private Ordinateur [] ordinateurs;
    private String[] columns={"Nom","Mac","Marque","Power","RAM","CPU","GPU","HDD","NomOS","Version"};
    private String[][] data;
    
    /**
     * Creates new form Tableau
     * @param ordinateurs
     */
    public Tableau(Ordinateur [] ordinateurs) {
        initComponents();
        this.ordinateurs=ordinateurs;        
        data=new String [ordinateurs.length][columns.length];
        //System.out.println("ligne: "+ordinateurs.length+" colonne: "+columns.length);
        tableau=new JTable(data,columns){
            public boolean isCellEditable(int date,int colums){
                return false;
            }            
        };
        initialiseTableau();
        tableau.setPreferredScrollableViewportSize(new Dimension(450,63));
        tableau.setFillsViewportHeight(true);
        JScrollPane jps=new JScrollPane(tableau);
        add(jps);
    }   
    
    public void initialiseTableau(){
        int i=0;
        for(Ordinateur ordi:ordinateurs){
            System.out.println("ORdinateur tab: "+ordi.toString());
            if(ordi!=null){
                int j=0;
                data[i][j]=ordi.getNom();
                 System.out.println(data[i][j]);
                j++;
               
                data[i][j]=ordi.getMac();
                 System.out.println(data[i][j]);
                j++;
                data[i][j]=ordi.getMarque();
                 System.out.println(data[i][j]);
                 j++;
                data[i][j]=(ordi.isPower()?"on":"off");
                 System.out.println(data[i][j]);
                 j++;
                data[i][j]=ordi.getRam();
                 System.out.println(data[i][j]);
                 j++;
                data[i][j]=ordi.getCpu();
                 System.out.println(data[i][j]);
                 j++;
                data[i][j]=ordi.getGpu();
                 System.out.println(data[i][j]);
                 j++;
                data[i][j]=ordi.getHdd();
                 System.out.println(data[i][j]);
                 j++;
                data[i][j]=(ordi.getOs().getNomOs());
                 System.out.println(data[i][j]);
                 j++;
                data[i][j]=(ordi.getOs().getVersion());
                 System.out.println(data[i][j]);
                i++;
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
