/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetreLocal;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import mesClasses.Tablette;

/**
 *
 * @author guigui
 */
public class TableauTablette extends javax.swing.JPanel {
    ArrayList<Tablette> tablettes;
    JTable tableau;
    private String[] columns={"Nom","Mac","Marque","Power","Capacité","Modele","NomOS","Version"};
    private String[][] data;
    /**
     * Creates new form FenetreTablette
     */
    public TableauTablette(ArrayList<Tablette> tablet) {
        //initComponents();
 
       this.tablettes=tablet;        
        data=new String [tablettes.size()][columns.length];
        //System.out.println("ligne: "+ordinateurs.length+" colonne: "+columns.length);
        initialiseTableau();
        tableau=new JTable(data,columns){
            public boolean isCellEditable(int date,int colums){
                return false;
            }            
        };
        
        tableau.setPreferredScrollableViewportSize(new Dimension(600,100));
        tableau.setFillsViewportHeight(true);
        add(tableau);
        JScrollPane jps=new JScrollPane(tableau);
        add(jps);
    }   
    
    public void initialiseTableau(){
        int i=0;
        for(Tablette tab:tablettes){        
            
            if (tab != null) {
                System.out.println("ORdinateur tab: "+tab.toString());
                int j = 0;
                data[i][j] = tab.getNom();
                j++;
                data[i][j] = tab.getMac();
                j++;
                data[i][j] = tab.getMarque();
                j++;
                data[i][j] = (tab.isPower() ? "on" : "off");
                j++;
                data[i][j] = tab.getCapacite();
                j++;
                data[i][j] = tab.getModele().toString();                           
                j++;
                data[i][j] = (tab.getOs().getNomOs());
                j++;
                data[i][j] = (tab.getOs().getVersion());
                i++;
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
